//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructuredTextParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructuredTextParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funktionen {0} med signaturen {1} redan definierad..
        /// </summary>
        internal static string ADDUSERDEFFNC {
            get {
                return ResourceManager.GetString("ADDUSERDEFFNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStatement() failed for array variable declaration..
        /// </summary>
        internal static string ARRAYVARDECL {
            get {
                return ResourceManager.GetString("ARRAYVARDECL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid type of declaration class..
        /// </summary>
        internal static string DECLARATION {
            get {
                return ResourceManager.GetString("DECLARATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStatement() failed for elementary variable declaration..
        /// </summary>
        internal static string ELEMVARDECL {
            get {
                return ResourceManager.GetString("ELEMVARDECL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate() failed: {0} is not a control variable..
        /// </summary>
        internal static string EVALUATE {
            get {
                return ResourceManager.GetString("EVALUATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate() failed: Control variable {0} not found in list..
        /// </summary>
        internal static string EVALUATE2 {
            get {
                return ResourceManager.GetString("EVALUATE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateFunctionBody() failed: Function body is null..
        /// </summary>
        internal static string GENFCNBODY {
            get {
                return ResourceManager.GetString("GENFCNBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateLoad() failed for data type {0}..
        /// </summary>
        internal static string GENLOADTYPE {
            get {
                return ResourceManager.GetString("GENLOADTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStore(): Invalid type of memory location of field..
        /// </summary>
        internal static string GENSTOREFIELD {
            get {
                return ResourceManager.GetString("GENSTOREFIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStore(): Memory location of field {0} not found..
        /// </summary>
        internal static string GENSTOREFIELD2 {
            get {
                return ResourceManager.GetString("GENSTOREFIELD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStore(): Invalid type of memory location of function block..
        /// </summary>
        internal static string GENSTOREFNCBLK {
            get {
                return ResourceManager.GetString("GENSTOREFNCBLK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStore(): Memory location of member {0} not found..
        /// </summary>
        internal static string GENSTOREFNCBLK2 {
            get {
                return ResourceManager.GetString("GENSTOREFNCBLK2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStatement() failed: l-value is null..
        /// </summary>
        internal static string LVALUE {
            get {
                return ResourceManager.GetString("LVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xABADFACE.
        /// </summary>
        internal static string MAGICNUMBER {
            get {
                return ResourceManager.GetString("MAGICNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.0.
        /// </summary>
        internal static string MAJORVERSION {
            get {
                return ResourceManager.GetString("MAJORVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeArrayInitializerList() failed: Array type expected..
        /// </summary>
        internal static string MAKEARRAYINITLIST {
            get {
                return ResourceManager.GetString("MAKEARRAYINITLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeArrayInitializerList() failed: Unknown type of array element..
        /// </summary>
        internal static string MAKEARRAYINITLIST2 {
            get {
                return ResourceManager.GetString("MAKEARRAYINITLIST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeAssignmentStatement(): StructInstanceSymbol expected..
        /// </summary>
        internal static string MAKEASSGNSTAT1 {
            get {
                return ResourceManager.GetString("MAKEASSGNSTAT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeAssignmentStatement(): ArrayInstanceSymbol expected..
        /// </summary>
        internal static string MAKEASSGNSTAT2 {
            get {
                return ResourceManager.GetString("MAKEASSGNSTAT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string MINORVERSION {
            get {
                return ResourceManager.GetString("MINORVERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryObject.GenerateStatement() failed: r-value is null..
        /// </summary>
        internal static string RVALUE {
            get {
                return ResourceManager.GetString("RVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryObject.GenerateAssignment() failed: rValue data type is Error.
        /// </summary>
        internal static string RVALUE2 {
            get {
                return ResourceManager.GetString("RVALUE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveFunctionBody() failed: Function definition list is empty..
        /// </summary>
        internal static string SAVEFCNBODY {
            get {
                return ResourceManager.GetString("SAVEFCNBODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveInitialValue() failed: Parameter objectList of invalid type..
        /// </summary>
        internal static string SAVEINITVALUE {
            get {
                return ResourceManager.GetString("SAVEINITVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreFieldsInReverse(): Memory location of field {0} not found..
        /// </summary>
        internal static string STOREFIELDREV {
            get {
                return ResourceManager.GetString("STOREFIELDREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreMembersInReverse(): Memory location of member {0} not found..
        /// </summary>
        internal static string STOREMEMREV {
            get {
                return ResourceManager.GetString("STOREMEMREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateStatement() failed for struct variable declaration..
        /// </summary>
        internal static string STRUCTVARDECL {
            get {
                return ResourceManager.GetString("STRUCTVARDECL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemoryObject.GenerateAssignment() failed: l-Value and r-Value have incompatible types..
        /// </summary>
        internal static string TYPERROR {
            get {
                return ResourceManager.GetString("TYPERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrapUpStructInitList(): Invalid type of struct initializer list..
        /// </summary>
        internal static string WRAPUPARRAYINILIST {
            get {
                return ResourceManager.GetString("WRAPUPARRAYINILIST", resourceCulture);
            }
        }
    }
}
